# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChianDoWebsite', '0004_auto_20160914_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
