# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChianDoWebsite', '0007_auto_20160914_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
