# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChianDoWebsite', '0008_blog_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChianDoWebsite.Picture'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
